### ISSUE TITLE
httpun-eio failing to build

### ISSUE THREAD

**Issue by ada2k** [anmonteiro/httpun#131]
This [commit](https://github.com/anmonteiro/httpun/commit/d6f8d6ca29a9f7a5d1d2c116a4fd6fc1a048d2dc#diff-616b165a722f602d35e183bb4732dee6aa04a6c4148adbcb172628ca5ea3a2db) changed a type of create_connection from `Eio_unix.Net.stream_socket_ty Eio.Net.stream_socket` to `_ Eio.Net.stream_socket`. This results, at least in a fresh 5.2.0 switch on my dev machine, in httpun-eio failing to build:

```
# Error: The implementation "eio/httpun_eio.ml"
# [...]
#             | `Flow
#             | `Platform of 'b
#             | `R
#             | `Shutdown
#             | `Socket
#             | `Stream
#             | `W ]"
#        The second variant type is open and the first is not
#        File "eio/httpun_eio.mli", lines 53-57, characters 2-8:
#          Expected declaration
#        File "eio/httpun_eio.ml", line 64, characters 6-23: Actual declaration
```

**Comment by anmonteiro** [comment]
You need gluten 0.5.1, pending merge on opam-repo

**Comment by anmonteiro** [comment]
https://github.com/ocaml/opam-repository/pull/26018

**Comment by ada2k** [comment]
Thank you!
